#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/immortalwrt-builder-stable.yml
# Description: Build ImmortalWRT using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
# Copyright (c) 2024-2025 SuperKali <hello@superkali.me>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: BananaWRT Builder (Stable)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      release_type: stable
      repo_branch: "24.10.4"
      config_file: config/stable/.config
      upload_bin_dir: false
      upload_package_dir: true
      upload_firmware: true
      upload_release: true
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
