#
# File: .github/workflows/immortalwrt-builder-nightly.yml
# Description: Build BananaWRT firmware (Nightly)
#
# Copyright (c) 2024-2025 SuperKali <hello@superkali.me>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: BananaWRT Builder (Nightly)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    uses: ./.github/workflows/immortalwrt-builder.yml
    with:
      immortalwrt_version: '25.12.0'
      release_type: nightly
    secrets: inherit
