#
# File: .github/workflows/immortalwrt-builder-stable.yml
# Description: Build BananaWRT firmware (Stable)
#
# Copyright (c) 2024-2025 SuperKali <hello@superkali.me>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: BananaWRT Builder (Stable)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    uses: ./.github/workflows/immortalwrt-builder.yml
    with:
      immortalwrt_version: '24.10.5'
      release_type: stable
    secrets: inherit
