name: Bump ImmortalWRT Version

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-bump:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Get the latest ImmortalWRT version
      id: get_latest_version
      run: |
        latest_version=$(curl -s https://api.github.com/repos/immortalwrt/immortalwrt/tags | jq -r '.[0].name' | sed 's/^v//')
        echo "latest_version=$latest_version" >> $GITHUB_ENV
        echo "Latest version: $latest_version"

    - name: Get the current versions
      id: get_current_versions
      run: |
        for file in .github/workflows/immortalwrt-builder*.yml; do
          current_version=$(grep 'REPO_BRANCH:' "$file" | awk '{print $2}')
          echo "$file:$current_version" >> current_versions.txt
        done
        echo "current_versions=$(cat current_versions.txt | tr '\n' ',')" >> $GITHUB_ENV
        echo "Current versions: $(cat current_versions.txt)"

    - name: Check if a bump is needed
      id: check_update
      run: |
        needs_update=false
        files_to_update=""
        while IFS= read -r line; do
          file=$(echo "$line" | cut -d':' -f1)
          current_version=$(echo "$line" | cut -d':' -f2)
          if [ "$current_version" != "${{ env.latest_version }}" ]; then
            echo "File $file needs update: $current_version -> ${{ env.latest_version }}"
            needs_update=true
            files_to_update="$files_to_update$file\n"
          fi
        done < current_versions.txt
        echo "needs_update=$needs_update" >> $GITHUB_ENV
        echo -e "$files_to_update" | sed '/^$/d' > files_to_update.txt
        if [ "$needs_update" = "false" ]; then
          echo "No bump needed."
        fi

    - name: Update REPO_BRANCH in YAML files
      if: env.needs_update == 'true'
      run: |
        while IFS= read -r file; do
          if [ -f "$file" ]; then
            sed -i "s/REPO_BRANCH: .*/REPO_BRANCH: ${{ env.latest_version }}/" "$file"
            echo "Updated REPO_BRANCH to ${{ env.latest_version }} in $file."
          else
            echo "Warning: File $file does not exist. Skipping."
          fi
        done < files_to_update.txt

    - name: Prepare list of updated files
      if: env.needs_update == 'true'
      run: |
        while IFS= read -r file; do
          echo "- $file" >> updated_files_list.txt
        done < files_to_update.txt

    - name: Create a pull request
      if: env.needs_update == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: bump-immortalwrt-${{ env.latest_version }}
        commit-message: 'Bump ImmortalWRT to version v${{ env.latest_version }}'
        title: 'Bump ImmortalWRT to version v${{ env.latest_version }}'
        body: |
          This pull request bumps ImmortalWRT to the latest version: v${{ env.latest_version }}.

          Changes:
          $(cat updated_files_list.txt)
        labels: bump, immortalwrt, v${{ env.latest_version }}
