#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/immortalwrt-builder-selfhost.yml
# Description: Build BananaWRT (Self Hosted) using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
# Copyright (c) 2024-2025 SuperKali <hello@superkali.me>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: BananaWRT Builder (Self Hosted)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Select the release type'
        required: true
        type: choice
        options:
          - stable
          - nightly
        default: stable
      architecture:
        description: 'Select the host architecture'
        required: true
        type: choice
        options:
          - X64
          - ARM64
        default: X64
      immortalwrt_version:
        description: 'Write the version of ImmortalWRT to use'
        type: string
        required: true
        default: '24.10.5'
      nproc:
        description: 'Specify the number of threads to use on the compiler'
        required: false
        default: ''

jobs:
  build:
    uses: ./.github/workflows/immortalwrt-builder.yml
    with:
      immortalwrt_version: ${{ github.event.inputs.immortalwrt_version }}
      release_type: ${{ github.event.inputs.release_type }}
      architecture: ${{ github.event.inputs.architecture }}
      nproc: ${{ github.event.inputs.nproc }}
    secrets: inherit
